### ISSUE TITLE
it seemd less a function "initialize_all_time_vectors()" ...

### ISSUE THREAD

**Issue by majiayuanyuan** [olesls/master_thesis#1]
hi ,
  thank you for sharing~~ but when i run the program， found It missed a function in lastfm_utils_ii_rnn.py  ,could you add the code of function ?  , it will do a lot good for me .
hope your reply soon :)

self.initialize_all_time_vectors(self.trainset_time_vectors, self.trainset, self.train_session_lengths)
self.initialize_all_time_vectors(self.testset_time_vectors, self.testset, self.test_session_lengths)

**Comment by olesls** [comment]
Hi

The problem should be fixed now. 

I did some experiments on using the time of the events in and between sessions to try to improve the results. I had forgotten to remove some of the code I used for this. 

Sorry about the terrible code. But just ask if there is anything I can help with :)

**Comment by majiayuanyuan** [comment]
I've solved this problem,thanks very much  :)
